services:
  mysql_usuarios:
    image: mysql:8.0
    container_name: mysql_usuarios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: genagena1
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_usuarios_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api_usuarios:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_usuarios_go
    depends_on:
      mysql_usuarios:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      DB_HOST: mysql_usuarios
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: genagena1
      DB_NAME: usuarios_db
    restart: on-failure

volumes:
  mysql_usuarios_data:
